In [2]:
import numpy as np
import pandas as pd

#### Import V_lambdas

In [4]:
df_Vn = pd.read_csv('4D_Vlam_6_4.dat',sep=',')

In [5]:
df_Vn

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,127279.774708,6465.972561,-8.529634e+00,196431.796801,21490.956328,-11954.359420,12970.261089,7.334888e+02,-3.903944e+02,1.986009e+02,...,2.098665e+03,6.225165e+04,18475.923726,-11975.928636,10765.318388,3.300626e+03,-2.030570e+03,1.518008e+03,-1.172321e+03,9.743316e+02
1,92703.871199,4774.114812,-5.336705e+00,143904.152697,15704.316846,-8745.024667,9513.852912,5.332785e+02,-2.830742e+02,1.425033e+02,...,1.514183e+03,4.592552e+04,13460.559213,-8721.853429,7834.269194,2.386643e+03,-1.468465e+03,1.098017e+03,-8.482828e+02,7.056869e+02
2,67365.266012,3522.024847,-3.156622e+00,105279.438895,11434.890712,-6376.956664,6962.054667,3.867602e+02,-2.045882e+02,1.015501e+02,...,1.088805e+03,3.386514e+04,9782.702045,-6337.743629,5690.760053,1.720474e+03,-1.058719e+03,7.918006e+02,-6.119314e+02,5.095492e+02
3,48820.945961,2595.647977,-1.692596e+00,76902.335050,8288.363853,-4631.412244,5079.617599,2.796941e+02,-1.472873e+02,7.172862e+01,...,7.798859e+02,2.495872e+04,7089.207666,-4593.365497,4125.402118,1.235880e+03,-7.606180e+02,5.689681e+02,-4.398651e+02,3.666080e+02
4,35269.834134,1910.489222,-7.310369e-01,56074.289026,5972.619246,-3346.373298,3692.332302,2.015899e+02,-1.055360e+02,5.008001e+01,...,5.560946e+02,1.838375e+04,5119.604493,-3319.013690,2984.053206,8.841557e+02,-5.442218e+02,4.071702e+02,-3.148701e+02,2.626514e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,-0.001153,-0.000158,-7.041444e-07,-0.000410,-0.002120,0.001034,-0.000816,-2.950043e-06,9.099252e-06,-2.264835e-05,...,2.580868e-05,-4.139748e-05,-0.000338,0.000063,0.000226,3.092822e-05,-1.739001e-05,1.043038e-05,-4.040223e-06,-4.091982e-06
73,-0.000424,-0.000058,-2.590462e-07,-0.000151,-0.000780,0.000380,-0.000300,-1.085205e-06,3.347399e-06,-8.331853e-06,...,9.494726e-06,-1.522824e-05,-0.000124,0.000023,0.000083,1.137820e-05,-6.397641e-06,3.837278e-06,-1.486431e-06,-1.505269e-06
74,-0.000156,-0.000021,-9.529860e-08,-0.000056,-0.000287,0.000140,-0.000110,-3.992174e-07,1.231436e-06,-3.065116e-06,...,3.492948e-06,-5.602013e-06,-0.000046,0.000008,0.000031,4.185855e-06,-2.353589e-06,1.411677e-06,-5.468431e-07,-5.537455e-07
75,-0.000057,-0.000008,-3.505850e-08,-0.000020,-0.000106,0.000051,-0.000041,-1.468629e-07,4.530193e-07,-1.127593e-06,...,1.284988e-06,-2.060846e-06,-0.000017,0.000003,0.000011,1.539896e-06,-8.658410e-07,5.193297e-07,-2.011745e-07,-2.037100e-07
76,-0.000021,-0.000003,-1.289732e-08,-0.000008,-0.000039,0.000019,-0.000015,-5.402769e-08,1.666564e-07,-4.148182e-07,...,4.727213e-07,-7.581404e-07,-0.000006,0.000001,0.000004,5.664971e-07,-3.185256e-07,1.910511e-07,-7.400824e-08,-7.494049e-08

#### Declare important variables and import Legendre Coeff numpy file

In [6]:
lm=28                        # Radial terms
nc=77                      # number of Radial coordinates (Must be same for all angles)
ngm = 112                    # number of angular coordinates
E_inf = -78.70465827  
px = np.zeros((ngm,lm))     # Matrix to stores legendre coeffinients

V_nf= np.zeros((nc,lm))     # Numpy 2D array to store generated potentials
V_nf2= np.zeros((ngm,nc))   # Numpy 2D array to store ab_initio potentials

In [7]:
px = np.load("4D_BiSp_coeff.npy")
V_n1 = px.dot(df_Vn.T)                 # save regenerated potentials

#### convert regenerated potentials into dataframe

In [8]:
a12 = np.arange(ngm)            # creates header for angles
df_Vnf = pd.DataFrame(V_n1.T, columns = a12) # saves final matrix into dataframe with appropriate header
df_Vnf                     # prints regenerated potentials

,0,1,2,3,4,5,6,7,8,9,...,102,103,104,105,106,107,108,109,110,111
0,426161.657409,96958.075953,6203.916603,1305.992642,6203.916603,96958.075953,426161.657409,391913.611500,95832.450917,5782.816338,...,4896.161192,91081.786432,336129.888755,314594.211919,89627.242179,4354.425536,466.609542,4354.425536,89627.242179,314594.211919
1,312530.241330,70832.511476,4401.872520,873.028833,4401.872520,70832.511476,312530.241330,287574.332115,69977.555065,4085.364835,...,3424.427742,66469.102883,246852.228719,231086.034538,65368.991551,3023.939648,220.464937,3023.939648,65368.991551,231086.034538
2,228902.737692,51645.465342,3100.535229,570.759778,3100.535229,51645.465342,228902.737692,210761.230416,50998.108942,2861.799796,...,2367.958296,48414.540092,181100.268898,169580.814655,47583.642192,2071.018840,57.314081,2071.018840,47583.642192,169580.814655
3,167404.711754,37569.544897,2164.177046,361.833441,2164.177046,37569.544897,167404.711754,154254.064543,37081.471459,1983.343688,...,1613.272991,35186.234544,132706.961104,124310.504876,34559.970705,1392.240986,-47.500464,1392.240986,34559.970705,124310.504876
4,122220.185627,27256.131090,1493.313733,219.221522,1493.313733,27256.131090,122220.185627,112719.371739,26890.270418,1355.656433,...,1077.337922,25506.981561,97116.219434,91013.881018,25036.348452,911.962647,-111.706615,911.962647,25036.348452,91013.881018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,-0.002268,-0.001287,-0.000149,0.000131,-0.000149,-0.001287,-0.002268,-0.001689,-0.000970,-0.000201,...,-0.000285,-0.000329,-0.000465,0.000181,-0.000081,-0.000376,-0.000340,-0.000376,-0.000081,0.000181
73,-0.000835,-0.000474,-0.000055,0.000048,-0.000055,-0.000474,-0.000835,-0.000621,-0.000357,-0.000074,...,-0.000105,-0.000121,-0.000171,0.000066,-0.000030,-0.000138,-0.000125,-0.000138,-0.000030,0.000066
74,-0.000307,-0.000174,-0.000020,0.000018,-0.000020,-0.000174,-0.000307,-0.000229,-0.000131,-0.000027,...,-0.000039,-0.000044,-0.000063,0.000024,-0.000011,-0.000051,-0.000046,-0.000051,-0.000011,0.000024
75,-0.000113,-0.000064,-0.000007,0.000007,-0.000007,-0.000064,-0.000113,-0.000084,-0.000048,-0.000010,...,-0.000014,-0.000016,-0.000023,0.000009,-0.000004,-0.000019,-0.000017,-0.000019,-0.000004,0.000009
76,-0.000042,-0.000024,-0.000003,0.000002,-0.000003,-0.000024,-0.000042,-0.000031,-0.000018,-0.000004,...,-0.000005,-0.000006,-0.000009,0.000003,-0.000001,-0.000007,-0.000006,-0.000007,-0.000001,0.000003

#### import ab initio potentials --> convert into dataframe --> find error

In [16]:
df_inp2 = pd.read_csv('4D_PES.dat',header=None,sep='\s+')       # importing ab initio data
df_inp2.sort_values(by = [0,1,2,3], inplace=True, ascending = True)
df_inp2.reset_index(inplace=True, drop = True)  # sorting by R, phi, th2 and th1 and reindexing
df_inp2

         0   1   2    3             4
0      2.5   0   0    0  4.242697e+05
1      2.5   0   0   30  9.804047e+04
2      2.5   0   0   60  6.253008e+03
3      2.5   0   0   90  1.281146e+03
4      2.5   0   0  120  6.323170e+03
...    ...  ..  ..  ...           ...
8619  20.0  90  90   60 -4.835570e-06
8620  20.0  90  90   90 -4.967355e-06
8621  20.0  90  90  120 -4.943375e-06
8622  20.0  90  90  150  7.493676e-07
8623  20.0  90  90  180  2.728643e-06

[8624 rows x 5 columns]

In [17]:
np.shape(V_nf2)

(112, 77)

In [18]:
for i in range (nc):            # loop over all R   
    ct = i*ngm                  # extract start point. Since input dataframe is sorted by R and theta, 
    f = df_inp2[4][ct:ct+ngm]   # potentials (V) are extracting for each R value at a time 
    V_nf2[:,i] = f           # ab initio data stored in 2D matrix one by one
V_nf2                        # visualizing numoy file

array([[ 4.24269734e+05,  3.11142932e+05,  2.27886716e+05, ...,
        -3.06397098e-04, -1.12716896e-04, -4.14661885e-05],
       [ 9.80404687e+04,  7.16113629e+04,  5.22038452e+04, ...,
        -1.71207954e-04, -6.29837974e-05, -2.31704321e-05],
       [ 6.25300812e+03,  4.43584533e+03,  3.12380830e+03, ...,
        -1.92934131e-05, -7.09763160e-06, -2.61107025e-06],
       ...,
       [ 4.41730256e+03,  3.08555968e+03,  2.13007159e+03, ...,
        -3.65269316e-05, -1.34374913e-05, -4.94337464e-06],
       [ 9.23386333e+04,  6.73887489e+04,  4.90902636e+04, ...,
         5.53672894e-06,  2.03695378e-06,  7.49367635e-07],
       [ 3.11824095e+05,  2.29071762e+05,  1.68119292e+05, ...,
         2.01613539e-05,  7.41714806e-06,  2.72864341e-06]])

In [35]:
df_Vnf2 = pd.DataFrame(V_nf2.T, columns = a12) # saves final matrix into dataframe with angular header
df_Vnf2

,0,1,2,3,4,5,6,7,8,9,...,102,103,104,105,106,107,108,109,110,111
0,424269.734133,98040.468659,6253.008116,1281.146077,6323.170408,97282.681157,424251.254699,390680.819034,93583.895927,6155.878359,...,4843.867693,90605.724749,338637.318943,314799.703531,8.858845e+04,4419.663829,519.672468,4417.302559,9.233863e+04,311824.094707
1,311142.932405,71611.362910,4435.845334,856.841829,4483.103772,71067.774656,311127.807343,286683.844545,68425.658618,4359.766065,...,3399.715847,66158.397661,248682.717477,231237.569327,6.467517e+04,3086.500856,270.262606,3085.559678,6.738875e+04,229071.761951
2,227886.716488,52203.845167,3123.808303,560.472614,3155.172768,51815.491306,227874.359398,210119.955735,49947.373303,3066.430703,...,2361.653370,48218.923554,182434.365949,169692.494815,4.713243e+04,2130.167852,103.496591,2130.071588,4.909026e+04,168119.292129
3,166661.663528,37968.173914,2179.926992,355.505825,2200.375156,37692.018474,166651.586521,153793.854194,36389.232947,2138.723255,...,1618.896356,35069.791888,133677.478298,124392.757094,3.427781e+04,1447.582737,-5.042575,1447.948596,3.568571e+04,123252.611300
4,121677.650821,27539.324124,1503.815006,215.500306,1516.860055,27344.012374,121669.448889,112390.405675,26452.665068,1476.288888,...,1090.355148,25444.192634,97820.776166,91074.412733,2.487062e+04,963.337298,-72.925446,963.916617,2.587921e+04,90250.234837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,-0.002264,-0.001265,-0.000143,0.000120,-0.000121,-0.001287,-0.002262,-0.001713,-0.000416,0.000086,...,-0.000235,-0.000309,-0.000446,0.000180,-5.271397e-06,-0.000264,-0.000271,-0.000270,4.088988e-05,0.000149
73,-0.000833,-0.000465,-0.000052,0.000044,-0.000045,-0.000473,-0.000832,-0.000630,-0.000153,0.000032,...,-0.000086,-0.000114,-0.000164,0.000066,-1.933897e-06,-0.000097,-0.000100,-0.000099,1.504828e-05,0.000055
74,-0.000306,-0.000171,-0.000019,0.000016,-0.000016,-0.000174,-0.000306,-0.000232,-0.000056,0.000012,...,-0.000032,-0.000042,-0.000060,0.000024,-7.107182e-07,-0.000036,-0.000037,-0.000037,5.536729e-06,0.000020
75,-0.000113,-0.000063,-0.000007,0.000006,-0.000006,-0.000064,-0.000113,-0.000085,-0.000021,0.000004,...,-0.000012,-0.000015,-0.000022,0.000009,-2.613608e-07,-0.000013,-0.000014,-0.000013,2.036954e-06,0.000007
76,-0.000041,-0.000023,-0.000003,0.000002,-0.000002,-0.000024,-0.000041,-0.000031,-0.000008,0.000002,...,-0.000004,-0.000006,-0.000008,0.000003,-9.613602e-08,-0.000005,-0.000005,-0.000005,7.493676e-07,0.000003

#### Warning! : Recreating 91 ab-initio angles from 4 radial coefficients. Ideally,
    {no of angular terms = no of V lambdas}

In [48]:
# Error at minima (approx location)
st, end = 25, 35
rmse_min = np.sqrt(np.mean(np.square(df_Vnf[st:end]-df_Vnf2[st:end])))
rmse_min.mean()

2.7852003715555194

In [50]:
# Error at high energy (approx location)
end = 25
rmse_min = np.sqrt(np.mean(np.square(df_Vnf[:end]-df_Vnf2[:end])))
rmse_min.mean()

339.7274847983188

In [49]:
# Error at asymptotic (approx location)
st = 35
rmse_min = np.sqrt(np.mean(np.square(df_Vnf[st:]-df_Vnf2[st:])))
rmse_min.mean()

0.5301717071539569