In [1]:
import numpy as np
import pandas as pd

#### Import V_lambdas

In [2]:
df_Vn = pd.read_csv('2D_Vlam.dat',sep=',')

In [3]:
df_Vn

              0            2           4           6
0   1256.895511  1025.120059  109.648713  136.071870
1    887.264354   793.555514  102.553127   58.351987
2    611.061814   581.225705   78.972119   25.401750
3    411.099894   411.871091   57.091952   10.889040
4    269.369246   284.128951   39.542237    4.470996
..          ...          ...         ...         ...
95    -0.005858    -0.003273    0.000129    0.000010
96    -0.005047    -0.001974   -0.000416    0.001024
97    -0.003658    -0.003119    0.000211   -0.000308
98    -0.002881    -0.002007   -0.000323    0.001012
99    -0.001723    -0.002852    0.000546   -0.000797

[100 rows x 4 columns]

#### Declare important variables and import Legendre Coeff numpy file

In [4]:
lm=4                        # Radial terms
nc=100                      # number of Radial coordinates (Must be same for all angles)
ngm = 91                    # number of angular coordinates (91 for symmetric molecule, 181 for non-symm.)
E_inf = -78.70465827  
px = np.zeros((ngm,lm))     # Matrix to stores legendre coeffinients

V_nf= np.zeros((nc,lm))     # Numpy 2D array to store generated potentials
V_nf2= np.zeros((ngm,nc))   # Numpy 2D array to store ab_initio potentials

In [5]:
px = np.load("2D_L_coeff.npy")
V_n1 = px.dot(df_Vn.T)                 # save regenerated potentials

#### convert regenerated potentials into dataframe

In [6]:
a12 = np.arange(ngm)            # creates header for angles
df_Vnf = pd.DataFrame(V_n1.T, columns = a12) # saves final matrix into dataframe with appropriate header
df_Vnf                     # prints regenerated potentials

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
0,2527.736153,2526.665972,2523.460840,2518.136942,2510.721097,2501.250533,2489.772559,2476.344169,2461.031549,2443.909520,...,791.062978,781.235906,772.446043,764.736429,758.145390,752.706110,748.446261,745.387693,743.546188,742.931289
1,1841.724982,1841.019792,1838.907111,1835.395590,1830.499572,1824.238983,1816.639186,1807.730784,1797.549392,1786.135373,...,539.391495,533.476475,528.211990,523.614447,519.698461,516.476688,513.959684,512.155787,511.071019,510.709024
2,1296.661388,1296.194417,1294.795126,1292.468364,1289.222179,1285.067762,1280.019373,1274.094250,1267.312488,1259.696915,...,360.205881,356.449631,353.118668,350.219006,347.756002,345.734296,344.157758,343.029445,342.351568,342.125459
3,890.951977,890.642077,889.713316,888.168515,886.012351,883.251339,879.893787,875.949752,871.430980,866.350840,...,234.822775,232.389091,230.236636,228.367252,226.782576,225.484028,224.472793,223.749805,223.315740,223.171006
4,597.511431,597.307125,596.694766,595.676026,594.253687,592.431620,590.214768,587.609123,584.621695,581.260474,...,148.306724,146.719462,145.318212,144.103237,143.074771,142.233016,141.578139,141.110274,140.829516,140.735924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-0.008992,-0.008990,-0.008987,-0.008980,-0.008972,-0.008960,-0.008946,-0.008930,-0.008911,-0.008890,...,-0.004307,-0.004280,-0.004256,-0.004235,-0.004217,-0.004203,-0.004192,-0.004183,-0.004179,-0.004177
96,-0.006414,-0.006416,-0.006421,-0.006429,-0.006441,-0.006456,-0.006474,-0.006494,-0.006516,-0.006540,...,-0.004419,-0.004441,-0.004462,-0.004481,-0.004497,-0.004511,-0.004522,-0.004530,-0.004535,-0.004536
97,-0.006873,-0.006871,-0.006865,-0.006854,-0.006840,-0.006821,-0.006799,-0.006773,-0.006743,-0.006709,...,-0.002103,-0.002066,-0.002033,-0.002004,-0.001980,-0.001960,-0.001944,-0.001933,-0.001926,-0.001923
98,-0.004199,-0.004201,-0.004206,-0.004215,-0.004228,-0.004243,-0.004262,-0.004283,-0.004307,-0.004333,...,-0.002209,-0.002229,-0.002247,-0.002264,-0.002279,-0.002292,-0.002302,-0.002309,-0.002313,-0.002315
99,-0.004827,-0.004824,-0.004814,-0.004800,-0.004779,-0.004752,-0.004720,-0.004683,-0.004640,-0.004593,...,-0.000115,-0.000060,-0.000010,0.000033,0.000071,0.000102,0.000126,0.000143,0.000154,0.000157

#### import ab initio potentials --> convert into dataframe --> find error

In [7]:
df_inp2 = pd.read_csv('2D_PES.dat',header=None,sep='\s+')       # importing ab initio data
df_inp2[2] = (df_inp2[2] - E_inf)*219474.63                     # convert to cm-1
df_inp2.sort_values(by = [ 0,1], inplace=True, ascending = True)    # sort by (R, theta) in ascending order

In [8]:
np.shape(V_nf2)

(91, 100)

In [9]:
for i in range (nc):            # loop over all R   
    ct = i*ngm                  # extract start point. Since input dataframe is sorted by R and theta, 
    f = df_inp2[2][ct:ct+ngm]   # potentials (V) are extracting for each R value at a time 
    V_nf2[:,i] = f           # ab initio data stored in 2D matrix one by one
V_nf2                        # visualizing numoy file

array([[ 2.64515653e+03,  1.87800051e+03,  1.30946685e+03, ...,
        -6.58424100e-03, -4.38949296e-03, -4.38949296e-03],
       [ 2.64081312e+03,  1.87650370e+03,  1.30866577e+03, ...,
        -6.58424100e-03, -4.38949296e-03, -4.38949296e-03],
       [ 2.63150959e+03,  1.87204178e+03,  1.30672780e+03, ...,
        -6.58424100e-03, -4.38949296e-03, -4.38949296e-03],
       ...,
       [ 7.75006619e+02,  5.23657688e+02,  3.47722435e+02, ...,
        -2.19474804e-03, -2.19474804e-03,  0.00000000e+00],
       [ 7.73880714e+02,  5.22854411e+02,  3.47160580e+02, ...,
        -2.19474804e-03, -2.19474804e-03,  0.00000000e+00],
       [ 7.73511996e+02,  5.22623963e+02,  3.46956469e+02, ...,
        -2.19474804e-03, -2.19474804e-03,  0.00000000e+00]])

In [10]:
df_Vnf2 = pd.DataFrame(V_nf2.T, columns = a12) # saves final matrix into dataframe with angular header
df_Vnf2

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
0,2645.156525,2640.813122,2631.509593,2615.856662,2595.561843,2569.863559,2540.190589,2507.581048,2472.743840,2436.866322,...,803.830222,797.454484,791.917139,787.029439,782.894537,779.514628,776.885322,775.006619,773.880714,773.511996
1,1878.000514,1876.503697,1872.041778,1866.140105,1857.688137,1846.828532,1834.206546,1819.857295,1803.754441,1786.699068,...,544.264161,539.703478,535.680508,532.197446,529.282823,526.870797,524.996483,523.657688,522.854411,522.623963
2,1309.466848,1308.665766,1306.727805,1303.448854,1298.984740,1293.245478,1286.426402,1278.681142,1269.983362,1260.122367,...,362.190203,358.988068,356.165624,353.722872,351.657615,349.969856,348.659592,347.722435,347.160580,346.956469
3,896.951113,894.795872,893.648019,891.764927,889.302422,885.990550,882.015864,877.406897,873.667049,867.677586,...,235.621379,233.413464,231.468919,229.785548,228.363353,227.202332,226.298096,225.655036,225.268760,225.126102
4,600.168739,598.961628,597.952045,596.891983,595.333713,593.336494,590.884962,588.025208,585.501249,581.833828,...,148.549209,147.052392,145.735544,144.596470,143.632977,143.029422,142.412698,141.973749,141.710379,141.613810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-0.008779,-0.008779,-0.008779,-0.008779,-0.008779,-0.008779,-0.008779,-0.008779,-0.008779,-0.008779,...,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389
96,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,...,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389
97,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,-0.006584,...,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195
98,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,...,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195,-0.002195
99,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,-0.004389,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

#### Warning! : Recreating 91 ab-initio angles from 4 radial coefficients. Ideally,
    {no of angular terms = no of V lambdas}

In [14]:
# Error at minima (approx location)
st, end = 10, 40
rmse_min = np.sqrt(np.mean(np.square(df_Vnf[st:end]-df_Vnf2[st:end])))
rmse_min.mean()

0.07725962381725983

In [12]:
# Error at high energy (approx location)
end = 10
rmse_min = np.sqrt(np.mean(np.square(df_Vnf[:end]-df_Vnf2[:end])))
rmse_min.mean()

12.689645770749555

In [13]:
# Error at asymptotic (approx location)
st = 40
rmse_min = np.sqrt(np.mean(np.square(df_Vnf[st:]-df_Vnf2[st:])))
rmse_min.mean()

0.0005873395789656107